version: '2.4'
services:
  cassandra:
    image: cassandra:3.11.2
    volumes:
      - "./cassandra-init.sh:/cassandra-init.sh"
    command: "sh /cassandra-init.sh"
    ports:
      - "127.0.0.1:9042:9042"

  product-api:
    image: product-api:latest
    ports:
      -  "127.0.0.1:8080:8080"
    depends_on:
      - cassandra